### PR TITLE
Change license to CC-BY-SA 4.0

### LINKED ISSUE #38: Please change to an open or free license
Hi, this idea is great!

Sadly, the current license, `Creative Commons Attribution-NoDerivs 3.0 Unported`, is neither Open Source nor Free Software. This is because it doesn't allow non-derivative works.

Could it be changed to an Open Source or Free Software license?
I propose `CC BY-SA 3.0`, https://creativecommons.org/licenses/by-sa/3.0/, which has a "share-alike" clause instead of a "non-derivative" clause.

(note that one needs the approval of all the contributors for such a change).

### PR DESCRIPTION
**Pull request by dcermak**
This fixes #38

Please do **not** merge this unless **every single** reviewer has approved this PR.

### CODE REVIEW

**Review by smarlowucf — APPROVED** [review]

**Review by bmwiedemann — APPROVED** [review]

**Review by asettle — APPROVED** [review]

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Review by jeremy-moffitt — APPROVED** [review]
Thanks for tackling this!

**Review by rsimai — APPROVED** [review]
thx for updating

**Review by ml8mr — APPROVED** [review]

**Review by aosthof — APPROVED** [review]
Fine by me.

**Comment by SheilaghM** [comment]
Works for me.

**Review by SheilaghM — APPROVED** [review]

**Pull request merged**
