### PR TITLE
recipe: add chicken and leek pie

### PR DESCRIPTION
**Pull request by asettle**
Signed-off-by: Alexandra Settle <asettle@suse.com>

### CODE REVIEW

**Review by rsimai — COMMENTED** [review]
Just found your change "entrees (main course, for those outside the US)" and I actually wanted to introduce another category "main" in my PR. I guess I'll revert my changes, thanks for clarification!

**Comment by asettle** [comment]
> Just found your change "entrees (main course, for those outside the US)" and I actually wanted to introduce another category "main" in my PR. I guess I'll revert my changes, thanks for clarification!

No problem :) took me ages to figure it out the first time I went to the US :joy:

**Review by rsimai — CHANGES_REQUESTED** [review]
You'e actually using "main" instead of "entree" in the path, after we clarified it's "entree" :-)

**Comment by asettle** [comment]
> You'e actually using "main" instead of "entree" in the path, after we clarified it's "entree" :-)

Ah! So I am. Force of habit. Thanks :smile:

**Comment by asettle** [comment]
Tbh, @rsimai, it might make sense in the long run to change it to "main" anyway. Only the US uses "entree" as a term for a main meal. I'll create an issue for it, since it would mean that we would need to change several files - but that can be done easily.

**Comment by asettle** [comment]
> Tbh, @rsimai, it might make sense in the long run to change it to "main" anyway. Only the US uses "entree" as a term for a main meal. I'll create an issue for it, since it would mean that we would need to change several files - but that can be done easily.

https://github.com/SUSE/recipebook/issues/14

**Comment by pgonin** [comment]
also worth to consider, I believe 'Entree' comes from French but it actually means 'Starter' which makes sense as the Entrée is the Entrance to your meal :)

**Comment by zoopster** [comment]
Since we're clarifying...entrée is actually a noun and is the "act" of entering and the "culinary use" seems to have originated by the British from what I understand...but then the term, in culinary sense, was oversimplified in the US for no other reason than to sound elegant which in some circles makes you appear smart which is rather dumb because it has nothing to do with a main course!!! and I have to say...this recipe sounds delicious!

**Review by rsimai — CHANGES_REQUESTED** [review]
your picture names are wrong (extensions), they won't work.

**Comment by asettle** [comment]
> your picture names are wrong (extensions), they won't work.

MY BAD

**Comment by asettle** [comment]
> your picture names are wrong (extensions), they won't work.

**Comment by rsimai** [comment]
I have one more, didn't notice earlier. You should have some

```
ifdef::env-github[]
:imagesdir: ../../images
endif::[]
ifndef::env-github[]
:imagesdir: images
endif::[]
```

on top after the id in your recipe file, to make the images work.

**Review by rsimai — APPROVED** [review]
Your contributor photo dimensions seems a bit weird (264, 245 is very squarish) but up to you :-)

**Comment by asettle** [comment]
> Your contributor photo dimensions seems a bit weird (264, 245 is very squarish) but up to you :-)

Super squarish! I need to adjust. If you don't mind, I'll merge and fix. I need to figure it out. The original image is WAY too big.

**Pull request merged**
