### PR TITLE
Simplify structure and remove cruft build process, add Mac & Cheese recipe

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
Update implementation to a single file with all of the recipes, remove leftover build crud

### CODE REVIEW

**Comment by rsimai** [comment]
You're proposing one file with all the recipes? That can grow big, not sure if it's preferred. I'm not opposed to it but actually find it handier to make each recipe a single file. I should add I prefer maildir over mbox, too :-)

**Comment by jeremy-moffitt** [comment]
> You're proposing one file with all the recipes? That can grow big, not sure if it's preferred. I'm not opposed to it but actually find it handier to make each recipe a single file. I should add I prefer maildir over mbox, too :-)

I misunderstood the suggestion earlier, I'll readjust this to have 1 main file, then individual recipes in their own files

**Comment by jeremy-moffitt** [comment]
Updated, happy to return the entrees/sides/desserts/beverages folders if preferred as well, just let me know

**Comment by rsimai** [comment]
I'm so sorry for adding confusion, and in particular in a review. Thanks for your work! If I get it right files can be put anywhere and recipes.adoc links to them and should also serve as a proper preview. Correct?

That's probably as easy as it can get but a contributor still need to access two files at least. It's not my area of expertise and I don't know if it's good practice but could we reduce this even more to only add the single recipe file (containing some category info) and auto-generate a master file from all available single recipe files? Or is that "easier than easy"?

**Comment by jeremy-moffitt** [comment]
> I'm so sorry for adding confusion, and in particular in a review. Thanks for your work! If I get it right files can be put anywhere and recipes.adoc links to them and should also serve as a proper preview. Correct?
> 
> That's probably as easy as it can get but a contributor still need to access two files at least. It's not my area of expertise and I don't know if it's good practice but could we reduce this even more to only add the single recipe file (containing some category info) and auto-generate a master file from all available single recipe files? Or is that "easier than easy"?

As far as I can tell, asciidoc cannot do multiple files in a single include:: statement...  I'm sure we could create some build infrastructure around it, but that might move back away from simplifying, and would require a build process to view the content. Right now someone can just open the recipes.adoc file in github or in chrome+asciidoctor (better result doing this way) and see everything.

**Comment by jeremy-moffitt** [comment]
moved recipes back into folders for organization and to make it easier to rebase if changes are made in the interim, pre-rebased in Karens recipe from #5

**Comment by jeremy-moffitt** [comment]
I think I have this at a better place... I did add requirement of the asciidoctor package to build locally, but thats a fairly svelte package compared to DAPS. README is updated as well

**Review by rsimai — APPROVED** [review]
I understand this is the simplest we can do, thanks for your work!

**Review by aosthof — APPROVED** [review]
LGTM, thanks Jeremy!

**Pull request merged**
